### ISSUE TITLE
restCall contentType

### ISSUE THREAD

**Issue by awhitford** [avadev/AvaTax-REST-V2-JS-SDK#135]
This [code](https://github.com/avadev/AvaTax-REST-V2-JS-SDK/blob/1872ee25a3d3b741393efc27820714b492c014d8/lib/AvaTaxClient.js#L87) looks invalid:
```javascript
	  var contentType = res.headers._headers['content-type'][0];
```
I don't see that `Headers` has a `_headers` property.
Also, not sure if the case of `Content-Type` matters, but the HTTP convention is `Content-Type` (not `content-type`).

I think it should be:
```javascript
	  var contentType = res.headers.get('Content-Type');
```

**Comment by rstrube** [comment]
We are actually running into this issue.  `rest.headers._headers['content-type']` causes an Error, because `_headers` is `undefined`.  Because it's `res.headers` is a JS `Map` the SDK should be using the `get()` function to retrieve items from the map.  Could the AvaTax developers comment on this? Perhaps the `_headers['xxx']` is a syntax I'm unaware of?
